Description: Uploads a computer configuration to the Jamf Pro Server and creates a Self Service Policy and Smart Group.
Identifier: com.github.eth-its-recipes.jamf.DeferSoftwareUpdates-90-0-profile
ParentRecipe: com.github.eth-its-recipes.jamf.DeferSoftwareUpdates-onlyMajor-Template-profile
MinimumVersion: "2.3"

Input:
  DEFERRAL_DAYS_MAJOR_UPDATES: "90"
  DEFERRAL_DAYS_MINOR_UPDATES: "0"
  DEFERRAL_DAYS_APP_UPDATES: "0"
