Description: Uploads the pkg to the JSS, and creates a Self-Service Policy available to members of a Testing group.
Identifier: com.github.eth-its-recipes.jamf.AppleConfigurator2-prod
MinimumVersion: "2.3"
ParentRecipe: com.github.eth-its-recipes.jamf.template-OS-exclude-max-prod

Input:
  NAME: Apple Configurator 2
  UNTESTED_RECIPE_IDENTIFIER: local.jamf.AppleConfigurator2
  SELFSERVICE_ICON: "%NAME% 2.15.png"
