Description: |
  Uploads a computer configuration to the Jamf Pro Server and creates a Self Service Policy and Smart Group.

  This profile is for the production version of BBEdit. At certain times, the license key changes, so we need a separate profile for untested and tested versions.

  Required override keys:
  - BBEDIT_14_SERIAL
  - BBEDIT_15_SERIAL
Identifier: com.github.eth-its-recipes.jamf.BBEdit-settings-prod-profile
MinimumVersion: "2.3"

Input:
  NAME: BBedit
  JSS_INVENTORY_NAME: "%NAME%.app"
  IDENTIFIER: com.barebones.bbedit
  USERS_GROUP_NAME: "%NAME% users"
  USERS_GROUP_TEMPLATE: SmartGroup-users.xml
  TEST_USERS_GROUP_NAME: "%NAME% test users"
  TEST_USERS_GROUP_TEMPLATE: SmartGroup-test-users.xml
  EXCLUSION_GROUP_NAME: "%TEST_USERS_GROUP_NAME%"
  PROFILE_CATEGORY: Application Settings
  PROFILE_NAME: "%NAME%"
  PROFILE_DESCRIPTION: License and settings for BBEdit
  ORGANIZATION: "%NAME%"
  PROFILE_TEMPLATE: Profile-1-group-1-exclusion.xml
  PROFILE_PAYLOAD: "%IDENTIFIER%.plist"
  REPLACE_PROFILE: "True"

Process:
  - Processor: com.github.grahampugh.jamf-upload.processors/JamfCategoryUploader
    Arguments:
      category_name: "%PROFILE_CATEGORY%"
      replace_category: "False"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfComputerGroupUploader
    Arguments:
      computergroup_template: "%TEST_USERS_GROUP_TEMPLATE%"
      computergroup_name: "%TEST_USERS_GROUP_NAME%"
      replace_group: "False"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfComputerGroupUploader
    Arguments:
      computergroup_template: "%USERS_GROUP_TEMPLATE%"
      computergroup_name: "%USERS_GROUP_NAME%"
      replace_group: "False"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfComputerProfileUploader
    Arguments:
      profile_name: "%PROFILE_NAME%"
      profile_category: "%PROFILE_CATEGORY%"
      profile_template: "%PROFILE_TEMPLATE%"
      payload: "%PROFILE_PAYLOAD%"
      identifier: "%IDENTIFIER%"
      organization: "%ORGANIZATION%"
      profile_description: "%PROFILE_DESCRIPTION%"
      profile_computergroup: "%USERS_GROUP_NAME%"
      replace_profile: "%REPLACE_PROFILE%"
