Description: |
  Uploads a computer configuration to the Jamf Pro Server and creates a Self Service Policy and Smart Group.

  Required overrides:
  - ORGANIZATION
  - SERIAL (this is the license key)
Identifier: com.github.eth-its-recipes.jamf.GraphicConverter10-profile
MinimumVersion: "2.3"

Input:
  NAME: GraphicConverter
  MAJOR_VERSION: "10"
  IDENTIFIER: com.lemkesoft.graphicconverter10
  PROFILE_CATEGORY: Application Settings
  PROFILE_TEMPLATE: Profile-1-group.xml
  PROFILE_NAME: "%NAME% %MAJOR_VERSION%"
  PROFILE_PAYLOAD: "%IDENTIFIER%.plist"
  PROFILE_DESCRIPTION: Licenses GraphicConverter %MAJOR_VERSION%.
  USERS_GROUP_NAME: "%NAME% %MAJOR_VERSION% users"
  PROFILE_GROUP_TEMPLATE: SmartGroup-users.xml
  TESTING_GROUP_NAME: Testing
  TESTING_GROUP_TEMPLATE: StaticGroup-testing.xml
  REPLACE_PROFILE: "True"

Process:
  - Processor: com.github.grahampugh.jamf-upload.processors/JamfCategoryUploader
    Arguments:
      category_name: "%PROFILE_CATEGORY%"
      replace_category: "False"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfComputerGroupUploader
    Arguments:
      computergroup_template: "%TESTING_GROUP_TEMPLATE%"
      computergroup_name: "%TESTING_GROUP_NAME%"
      replace_group: "False"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfComputerGroupUploader
    Arguments:
      computergroup_template: "%PROFILE_GROUP_TEMPLATE%"
      computergroup_name: "%USERS_GROUP_NAME%"
      replace_group: "False"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfComputerProfileUploader
    Arguments:
      profile_name: "%PROFILE_NAME%"
      profile_category: "%PROFILE_CATEGORY%"
      profile_template: "%PROFILE_TEMPLATE%"
      payload: "%PROFILE_PAYLOAD%"
      identifier: "%IDENTIFIER%"
      organization: "%ORGANIZATION%"
      profile_description: "%PROFILE_DESCRIPTION%"
      profile_computergroup: "%USERS_GROUP_NAME%"
      replace_profile: "%REPLACE_PROFILE%"
