Comment: INTERNAL_COLLATERAL_URL key must be added to the recipe override.
Description: Uploads a computer configuration to the Jamf Pro Server and creates a Self Service Policy and Smart Group.
Identifier: com.github.eth-its-recipes.jamf.MicrosoftAutoUpdate-autoupdate-prod-profile
MinimumVersion: "2.3"

Input:
  NAME: Auto-update Microsoft AutoUpdate - production
  USERS_GROUP_NAME: Microsoft applications auto-update
  USERS_GROUP_TEMPLATE: SmartGroup-users-MicrosoftAutoUpdate.xml
  USERS_GROUP_ALL_MICROSOFT_APPS_NAME: Microsoft applications users
  USERS_GROUP_ALL_MICROSOFT_APPS_TEMPLATE: SmartGroup-users-Microsoft-all-apps.xml
  IDENTIFIER: com.microsoft.autoupdate2
  ORGANIZATION: ETH Zürich
  PROFILE_CATEGORY: Application Settings
  PROFILE_DESCRIPTION: Update settings for Microsoft AutoUpdate. This profile will detect and download updates directly from Microsoft's servers based on the "Custom" channel, the contents of which are determined by internal testing at ETH.
  PROFILE_NAME: "%NAME%"
  PROFILE_PAYLOAD: MicrosoftAutoUpdate-autoupdate-deadline-prod.plist
  PROFILE_TEMPLATE: Profile-MicrosoftAutoUpdate-autoupdate-prod.xml
  REPLACE_PROFILE: "True"
  UNTESTED_RECIPE_IDENTIFIER: local.jamf.MicrosoftOffice

Process:
  - Processor: com.github.grahampugh.recipes.preprocessors/LastRecipeRunChecker
    Arguments:
      recipeoverride_identifier: "%UNTESTED_RECIPE_IDENTIFIER%"

  - Processor: com.github.eth-its-recipes.processors/MSOfficeVersionSplitter

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfCategoryUploader
    Arguments:
      category_name: "%PROFILE_CATEGORY%"
      replace_category: "False"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfComputerGroupUploader
    Arguments:
      computergroup_template: "%USERS_GROUP_ALL_MICROSOFT_APPS_TEMPLATE%"
      computergroup_name: "%USERS_GROUP_ALL_MICROSOFT_APPS_NAME%"
      replace_group: "False"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfComputerGroupUploader
    Arguments:
      computergroup_template: "%USERS_GROUP_TEMPLATE%"
      computergroup_name: "%USERS_GROUP_NAME%"
      replace_group: "False"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfComputerProfileUploader
    Arguments:
      profile_name: "%PROFILE_NAME%"
      profile_category: "%PROFILE_CATEGORY%"
      profile_template: "%PROFILE_TEMPLATE%"
      payload: "%PROFILE_PAYLOAD%"
      identifier: "%IDENTIFIER%"
      organization: "%ORGANIZATION%"
      profile_description: "%PROFILE_DESCRIPTION%"
      replace_profile: "%REPLACE_PROFILE%"
