Description: Uploads a Mac App Store app configuration to the Jamf Pro Server.
Identifier: com.github.eth-its-recipes.jamf.AppleConfigurator2-macapp
MinimumVersion: "2.3"
ParentRecipe: com.github.eth-its-recipes.jamf.FreeMacApps-macapp

Input:
  NAME: Apple Configurator 2
