Description: Uploads a script to the Jamf Pro Server and creates a Self Service Policy and Smart Group.
Identifier: com.github.eth-its-recipes.jamf.AppleConfigurator-uninstall
MinimumVersion: "2.3"
ParentRecipe: com.github.eth-its-recipes.jamf.template-script-uninstall-no-users

Input:
  NAME: Apple Configurator
  SELFSERVICE_DESCRIPTION: "Uninstalls %NAME%"
  PARAMETER5_LABEL: Package Receipt
  PARAMETER5_VALUE: com.apple.pkg.ConfigurationUtility
  SELFSERVICE_ICON: "Apple Configurator 2 2.15.png"
