Description: Uploads a script to the Jamf Pro Server and creates a Self Service Policy and Smart Group.
Identifier: com.github.eth-its-recipes.jamf.ETHKerberosSettings-uninstall
MinimumVersion: "2.3"
ParentRecipe: com.github.eth-its-recipes.jamf.template-script-no-app-uninstall

Input:
  NAME: ETH Kerberos Settings
  SCRIPT_NAME: ETHKerberosSettings-uninstall.zsh
  SCRIPT_PATH: ETHKerberosSettings-uninstall.zsh
  EXTENSION_ATTRIBUTE_NAME: ETH Kerberos Settings
  EXTENSION_ATTRIBUTE_SEARCH_TYPE: matches regex
  EXTENSION_ATTRIBUTE_VALUE: "^Installed$"
  INSTALLED_GROUP_TEMPLATE: SmartGroup-installed-EA.xml
  SELFSERVICE_ICON: "%NAME%.png"
  TRIGGER_UNINSTALL_POLICY_TEMPLATE: Policy-uninstall-triggeronly-script.xml
