Description: Creates a Once per computer policy to update the Prism license by running the postinstall script.
Identifier: ch.ethz.id.jamf.script.PrivilegesConfiguration
MinimumVersion: "2.3"

Input:
  NAME: Privileges Configuration
  SCRIPT_CATEGORY: Tools & Accessories
  TRIGGER_POLICY_CATEGORY: Triggered Installers
  TRIGGER_POLICY_TEMPLATE: Policy-script-triggeronly-nonotification.xml
  TRIGGER_POLICY_NAME: Privileges Configuration
  TRIGGER_NAME: PrivilegesConfiguration-install
  SCRIPT_NAME: Privileges-postinstall.sh
  SCRIPT_PRIORITY: After
  PARAMETER4_LABEL: "Elevation Time (minutes)"
  TRIGGER_POLICY_RUN_COMMAND: "echo 'Installation of %NAME% complete'"

Process:
  - Processor: com.github.grahampugh.jamf-upload.processors/JamfCategoryUploader
    Arguments:
      category_name: "%SCRIPT_CATEGORY%"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfCategoryUploader
    Arguments:
      category_name: "%TRIGGER_POLICY_CATEGORY%"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfScriptUploader
    Arguments:
      script_category: "%SCRIPT_CATEGORY%"
      script_path: "%SCRIPT_NAME%"
      script_priority: "%SCRIPT_PRIORITY%"
      script_parameter4: "%PARAMETER4_LABEL%"
      replace_script: "True"

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfPolicyUploader
    Arguments:
      policy_template: "%TRIGGER_POLICY_TEMPLATE%"
      policy_name: "%TRIGGER_POLICY_NAME%"
      replace_policy: "False"
